"""
Project the canonical hot layer into a small always-resident core plus
on-demand topic files.

`GLOBAL_MEMORY.md` is loaded in full into every Claude Code session, so its
size is a hard cost paid on every turn. This module derives two things from it:

  core/CLAUDE_CORE.md   hard constraints + an index of topic files
  core/topics/*.md      one file per per-project section

The core is what syncs to ~/.claude/CLAUDE.md. Topic bodies are read only when
something needs them, which is what makes the archive able to grow without
charging the context window for it.

Projection is one-way and the output is disposable: GLOBAL_MEMORY.md stays the
single source of truth and is what harvest merges into. Nothing here edits it.
See docs/progressive-disclosure-memory-design.md for why derived projection was
chosen over letting the model own a file tree directly.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from memsync.config import Config

CORE_DIRNAME = "core"
TOPICS_DIRNAME = "topics"
CORE_FILENAME = "CLAUDE_CORE.md"

# Claude Code truncates a skill's description + when_to_use at 1,536 chars in the
# skill listing. That listing is the only part resident at session start, so it
# is the real budget for the whole memory index.
SKILL_DESCRIPTION_CAP = 1536

_HEADING_RE = re.compile(r"^(#{1,6})\s+(.*?)\s*$")
_CONSTRAINTS_RE = re.compile(r"^##\s+(Hard constraints|Constraints)\s*$", re.IGNORECASE)

_GENERATED_BANNER = (
    "<!-- Generated by memsync. Do not edit: regenerated from GLOBAL_MEMORY.md "
    "on every write. Edit the source, not this file. -->"
)


class ProjectionTooLarge(Exception):
    """The generated core exceeds its configured budget."""


@dataclass
class Section:
    """One heading and the body lines beneath it, up to the next heading."""

    level: int
    title: str
    body: list[str] = field(default_factory=list)

    @property
    def text(self) -> str:
        heading = f"{'#' * self.level} {self.title}"
        return "\n".join([heading, *self.body]).rstrip() + "\n"

    @property
    def is_constraints(self) -> bool:
        return bool(_CONSTRAINTS_RE.match(f"{'#' * self.level} {self.title}"))

    @property
    def bullets(self) -> list[str]:
        return [ln.strip() for ln in self.body if ln.strip()[:1] in ("-", "*", "+")]


@dataclass
class Topic:
    slug: str
    title: str
    description: str
    content: str


@dataclass
class Projection:
    core: str
    topics: list[Topic]
    preamble: str = ""

    @property
    def core_chars(self) -> int:
        return len(self.core)

    @property
    def core_lines(self) -> int:
        return len(self.core.splitlines())


def split_sections(text: str) -> tuple[str, list[Section]]:
    """
    Split markdown into (preamble, sections). Preamble is everything before the
    first heading — usually a version comment, sometimes nothing.
    """
    preamble: list[str] = []
    sections: list[Section] = []
    current: Section | None = None

    for line in text.splitlines():
        match = _HEADING_RE.match(line)
        if match:
            current = Section(level=len(match.group(1)), title=match.group(2))
            sections.append(current)
            continue
        if current is None:
            preamble.append(line)
        else:
            current.body.append(line)

    return "\n".join(preamble).strip(), sections


def slugify(title: str) -> str:
    """
    Filename-safe slug for a section title. Strips markdown emphasis and any
    parenthetical, which on real titles is usually a status note
    ("Memsync (active)") rather than identifying information.
    """
    text = re.sub(r"[*_`]", "", title)
    text = re.sub(r"\([^)]*\)", " ", text)
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", "-", text).strip("-")
    return (text or "untitled")[:60].rstrip("-")


def describe(section: Section, max_chars: int = 140) -> str:
    """
    One-line description for the index, derived from the section's first bullet.

    The index is the only thing resident in context, so this line is what a
    later session uses to decide whether the topic file is worth reading. It is
    truncated on a word boundary rather than mid-token.
    """
    first = next((b for b in section.bullets), "")
    text = re.sub(r"^[-*+]\s+", "", first)
    # Backticks and asterisks only. Underscores are identifiers far more often
    # than emphasis here (snake_case repo names, claude_code, SESSION_HANDOFF.md),
    # and stripping them silently rewrites paths into ones that do not exist.
    text = re.sub(r"[*`]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    if not text:
        return "No summary available."
    if len(text) <= max_chars:
        return text
    cut = text[:max_chars].rsplit(" ", 1)[0].rstrip(",;:.")
    return f"{cut}…"


def _topic_file(section: Section, description: str) -> str:
    """
    A topic file carries frontmatter so its purpose is legible without reading
    the body — the same convention Letta's context repositories and Claude
    Code's auto-memory topic files use.
    """
    title = re.sub(r'"', "'", section.title)
    return (
        "---\n"
        f'title: "{title}"\n'
        f'description: "{re.sub(chr(34), chr(39), description)}"\n'
        "source: GLOBAL_MEMORY.md\n"
        "---\n\n"
        f"{_GENERATED_BANNER}\n\n"
        f"{section.text}"
    )


def build_projection(hot: str, config: Config, topics_dir: Path | None = None) -> Projection:
    """
    Derive the core and topic files from the canonical hot layer.

    Hard constraints stay in the core in full. A constraint that has to be
    fetched is a constraint that will be missed, so it is never projected out
    however large the section grows — if it does not fit, that is a budget
    failure to surface, not a rule to hide.
    """
    preamble, sections = split_sections(hot)

    constraints = [s for s in sections if s.is_constraints]
    rest = [s for s in sections if not s.is_constraints]

    topics: list[Topic] = []
    used: set[str] = set()
    for section in rest:
        slug = slugify(section.title)
        # Distinct sections can slugify identically once parentheticals are
        # stripped; suffix rather than silently overwrite one with the other.
        if slug in used:
            n = 2
            while f"{slug}-{n}" in used:
                n += 1
            slug = f"{slug}-{n}"
        used.add(slug)
        description = describe(section)
        topics.append(
            Topic(
                slug=slug,
                title=section.title,
                description=description,
                content=_topic_file(section, description),
            )
        )

    parts: list[str] = [_GENERATED_BANNER]
    if preamble:
        parts.append(preamble)
    for section in constraints:
        parts.append(section.text.rstrip())
    if topics:
        if config.skill_enabled:
            # The skill listing carries the index instead, at a fraction of the
            # resident cost, so the core only needs a pointer.
            parts.append(_render_pointer(config.skill_name, len(topics)))
        else:
            parts.append(_render_index(topics, topics_dir))

    core = "\n\n".join(parts).rstrip() + "\n"
    return Projection(core=core, topics=topics, preamble=preamble)


def _render_pointer(skill_name: str, count: int) -> str:
    return (
        "## Memory index\n\n"
        f"Detail on {count} active projects and areas is not in this context. "
        f"It lives in the `{skill_name}` skill — invoke it, or read the topic "
        "file it names, when one of those areas comes up."
    )


def _render_index(topics: list[Topic], topics_dir: Path | None) -> str:
    """
    The index is the whole read path in phase 1: it carries absolute paths so a
    session can open a topic with ordinary file tools the moment it needs one.
    """
    lines = [
        "## Memory index",
        "",
        "Detail for each area below lives in its own file, not in this context. "
        "Read the file when the topic comes up.",
        "",
    ]
    for topic in topics:
        path = str(topics_dir / f"{topic.slug}.md") if topics_dir else f"{topic.slug}.md"
        lines.append(f"- **{topic.title}** — {topic.description}")
        lines.append(f"  `{path}`")
    return "\n".join(lines)


def short_title(title: str) -> str:
    """
    Title trimmed to its identifying part, for the packed keyword list in the
    skill description. Drops parentheticals and anything after a dash, which on
    real titles is status commentary ("Phase 5 in progress (NOT complete)")
    rather than something a session would search on.
    """
    text = re.sub(r"[*_`]", "", title)
    text = re.sub(r"\([^)]*\)", "", text)
    text = re.split(r"\s+[—–-]\s+", text)[0]
    return re.sub(r"\s+", " ", text).strip() or title.strip()


def build_skill_description(topics: list[Topic], cap: int = SKILL_DESCRIPTION_CAP) -> str:
    """
    The routing text Claude sees at session start. Everything else about this
    skill costs nothing until it is invoked, so this string is where the whole
    design either works or doesn't: it has to be enough for Claude to recognise
    that a question is about one of these areas, within `cap` characters.

    Topics are packed in order and the remainder is counted rather than silently
    dropped, so a memory that outgrows the cap says so instead of quietly
    becoming unroutable.
    """
    head = (
        "Long-term memory: standing detail on the user's active projects, "
        "clients and infrastructure that is deliberately not in CLAUDE.md. "
        "Use when a session touches any of: "
    )
    names = [short_title(t.title) for t in topics]
    if not names:
        return head.rstrip().rstrip(":") + " (no topics recorded yet)."

    kept: list[str] = []
    for i, name in enumerate(names):
        remaining = len(names) - i - 1
        # Reserve room for the overflow note before committing to another name.
        tail = f", and {remaining} more area(s)." if remaining else "."
        candidate = head + "; ".join([*kept, name]) + tail
        if len(candidate) > cap:
            break
        kept.append(name)

    dropped = len(names) - len(kept)
    tail = f", and {dropped} more area(s)." if dropped else "."
    return head + "; ".join(kept) + tail


def _yaml_double_quoted(value: str) -> str:
    """
    Emit a value as a YAML double-quoted scalar.

    Quoting is not optional here: the description reads naturally as
    "Long-term memory: standing detail…", and a plain scalar containing ": "
    parses as a nested mapping, which breaks the frontmatter rather than
    degrading it. Titles can also carry backslashes (Windows paths), which a
    double-quoted scalar treats as escapes.
    """
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    escaped = re.sub(r"\s*\n\s*", " ", escaped)
    return f'"{escaped}"'


def render_skill(projection: Projection, config: Config) -> str:
    """
    SKILL.md for the memory skill: frontmatter plus an index of topic files.

    The body stays in context for the rest of the turn once loaded, so it is an
    index and nothing else. Bodies live in topics/ and are read individually.
    """
    description = build_skill_description(projection.topics)
    lines = [
        "---",
        f"name: {config.skill_name}",
        f"description: {_yaml_double_quoted(description)}",
        "---",
        "",
        _GENERATED_BANNER,
        "",
        f"# {config.skill_name}",
        "",
        "Each area below has its own file in `topics/`. Read only the ones the "
        "current task needs.",
        "",
    ]
    for topic in projection.topics:
        lines.append(f"- `topics/{topic.slug}.md` — **{topic.title}**: {topic.description}")
    lines += [
        "",
        "These files are generated from the user's global memory. To change what "
        "they say, edit the source memory and re-run `memsync project`; edits "
        "made here are overwritten.",
    ]
    return "\n".join(lines) + "\n"


def check_budget(projection: Projection, config: Config) -> list[str]:
    """
    Return budget violations as human-readable strings. Empty list means the
    core fits.

    This is the check that did not exist: max_hot_lines was only ever
    interpolated into a prompt, so the file ran 2.4x over its stated target
    with nothing objecting.
    """
    problems: list[str] = []
    if projection.core_chars > config.core_max_chars:
        problems.append(
            f"core is {projection.core_chars:,} chars, over the "
            f"{config.core_max_chars:,} budget by "
            f"{projection.core_chars - config.core_max_chars:,}"
        )
    if projection.core_lines > config.max_hot_lines:
        problems.append(
            f"core is {projection.core_lines} lines, over the "
            f"{config.max_hot_lines} budget by "
            f"{projection.core_lines - config.max_hot_lines}"
        )
    return problems


def projection_root(config: Config) -> Path:
    """
    Where generated output goes. Machine-local, never the synced store.

    Projection output is derived, disposable, and machine-specific: it names
    absolute paths and every machine regenerates it from the same source. Put it
    in the synced store and two things break — the paths are wrong on every
    other machine, and each machine's rewrite syncs back as a change, so the
    file ping-pongs. Only GLOBAL_MEMORY.md and MEMORY_ARCHIVE.md need to travel.
    """
    if config.projection_root is not None:
        return Path(config.projection_root).expanduser()
    return Path.home() / ".claude" / "memsync"


def skill_root(config: Config) -> Path:
    if config.skill_root is not None:
        return Path(config.skill_root).expanduser()
    return Path.home() / ".claude" / "skills" / config.skill_name


def core_path(config: Config) -> Path:
    return projection_root(config) / CORE_FILENAME


def topics_path(config: Config) -> Path:
    """Topic files live inside the skill so SKILL.md can name them relatively."""
    if config.skill_enabled:
        return skill_root(config) / TOPICS_DIRNAME
    return projection_root(config) / TOPICS_DIRNAME


def _write_topics(projection: Projection, topics_dir: Path) -> list[Path]:
    """
    Write topic files and remove any that no longer correspond to a section.

    Stale removal is scoped to *.md directly inside topics/ — the directory is
    memsync-owned and regenerated, but the deletion is still kept narrow.
    """
    topics_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    expected = {f"{t.slug}.md" for t in projection.topics}

    for topic in projection.topics:
        target = topics_dir / f"{topic.slug}.md"
        target.write_text(topic.content, encoding="utf-8")
        written.append(target)

    for existing in topics_dir.glob("*.md"):
        if existing.name not in expected:
            existing.unlink()
    return written


def write_projection(projection: Projection, config: Config) -> list[Path]:
    """Write the core, the topic files, and the skill. Returns paths written."""
    core = core_path(config)
    core.parent.mkdir(parents=True, exist_ok=True)

    written = _write_topics(projection, topics_path(config))

    if config.skill_enabled:
        skill_dir = skill_root(config)
        skill_dir.mkdir(parents=True, exist_ok=True)
        skill_file = skill_dir / "SKILL.md"
        skill_file.write_text(render_skill(projection, config), encoding="utf-8")
        written.append(skill_file)

    core.write_text(projection.core, encoding="utf-8")
    written.append(core)
    return written
