"""
Project the canonical hot layer into a small always-resident core plus
on-demand topic files.

`GLOBAL_MEMORY.md` is loaded in full into every Claude Code session, so its
size is a hard cost paid on every turn. This module derives two things from it:

  core/CLAUDE_CORE.md   hard constraints + an index of topic files
  core/topics/*.md      one file per per-project section

The core is what syncs to ~/.claude/CLAUDE.md. Topic bodies are read only when
something needs them, which is what makes the archive able to grow without
charging the context window for it.

Projection is one-way and the output is disposable: GLOBAL_MEMORY.md stays the
single source of truth and is what harvest merges into. Nothing here edits it.
See docs/progressive-disclosure-memory-design.md for why derived projection was
chosen over letting the model own a file tree directly.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

from memsync.config import Config

CORE_DIRNAME = "core"
TOPICS_DIRNAME = "topics"
CORE_FILENAME = "CLAUDE_CORE.md"

_HEADING_RE = re.compile(r"^(#{1,6})\s+(.*?)\s*$")
_CONSTRAINTS_RE = re.compile(r"^##\s+(Hard constraints|Constraints)\s*$", re.IGNORECASE)

_GENERATED_BANNER = (
    "<!-- Generated by memsync. Do not edit: regenerated from GLOBAL_MEMORY.md "
    "on every write. Edit the source, not this file. -->"
)


class ProjectionTooLarge(Exception):
    """The generated core exceeds its configured budget."""


@dataclass
class Section:
    """One heading and the body lines beneath it, up to the next heading."""

    level: int
    title: str
    body: list[str] = field(default_factory=list)

    @property
    def text(self) -> str:
        heading = f"{'#' * self.level} {self.title}"
        return "\n".join([heading, *self.body]).rstrip() + "\n"

    @property
    def is_constraints(self) -> bool:
        return bool(_CONSTRAINTS_RE.match(f"{'#' * self.level} {self.title}"))

    @property
    def bullets(self) -> list[str]:
        return [ln.strip() for ln in self.body if ln.strip()[:1] in ("-", "*", "+")]


@dataclass
class Topic:
    slug: str
    title: str
    description: str
    content: str


@dataclass
class Projection:
    core: str
    topics: list[Topic]
    preamble: str = ""

    @property
    def core_chars(self) -> int:
        return len(self.core)

    @property
    def core_lines(self) -> int:
        return len(self.core.splitlines())


def split_sections(text: str) -> tuple[str, list[Section]]:
    """
    Split markdown into (preamble, sections). Preamble is everything before the
    first heading — usually a version comment, sometimes nothing.
    """
    preamble: list[str] = []
    sections: list[Section] = []
    current: Section | None = None

    for line in text.splitlines():
        match = _HEADING_RE.match(line)
        if match:
            current = Section(level=len(match.group(1)), title=match.group(2))
            sections.append(current)
            continue
        if current is None:
            preamble.append(line)
        else:
            current.body.append(line)

    return "\n".join(preamble).strip(), sections


def slugify(title: str) -> str:
    """
    Filename-safe slug for a section title. Strips markdown emphasis and any
    parenthetical, which on real titles is usually a status note
    ("Memsync (active)") rather than identifying information.
    """
    text = re.sub(r"[*_`]", "", title)
    text = re.sub(r"\([^)]*\)", " ", text)
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", "-", text).strip("-")
    return (text or "untitled")[:60].rstrip("-")


def describe(section: Section, max_chars: int = 140) -> str:
    """
    One-line description for the index, derived from the section's first bullet.

    The index is the only thing resident in context, so this line is what a
    later session uses to decide whether the topic file is worth reading. It is
    truncated on a word boundary rather than mid-token.
    """
    first = next((b for b in section.bullets), "")
    text = re.sub(r"^[-*+]\s+", "", first)
    text = re.sub(r"[*_`]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    if not text:
        return "No summary available."
    if len(text) <= max_chars:
        return text
    cut = text[:max_chars].rsplit(" ", 1)[0].rstrip(",;:.")
    return f"{cut}…"


def _topic_file(section: Section, description: str) -> str:
    """
    A topic file carries frontmatter so its purpose is legible without reading
    the body — the same convention Letta's context repositories and Claude
    Code's auto-memory topic files use.
    """
    title = re.sub(r'"', "'", section.title)
    return (
        "---\n"
        f'title: "{title}"\n'
        f'description: "{re.sub(chr(34), chr(39), description)}"\n'
        "source: GLOBAL_MEMORY.md\n"
        "---\n\n"
        f"{_GENERATED_BANNER}\n\n"
        f"{section.text}"
    )


def build_projection(hot: str, config: Config, topics_dir: Path | None = None) -> Projection:
    """
    Derive the core and topic files from the canonical hot layer.

    Hard constraints stay in the core in full. A constraint that has to be
    fetched is a constraint that will be missed, so it is never projected out
    however large the section grows — if it does not fit, that is a budget
    failure to surface, not a rule to hide.
    """
    preamble, sections = split_sections(hot)

    constraints = [s for s in sections if s.is_constraints]
    rest = [s for s in sections if not s.is_constraints]

    topics: list[Topic] = []
    used: set[str] = set()
    for section in rest:
        slug = slugify(section.title)
        # Distinct sections can slugify identically once parentheticals are
        # stripped; suffix rather than silently overwrite one with the other.
        if slug in used:
            n = 2
            while f"{slug}-{n}" in used:
                n += 1
            slug = f"{slug}-{n}"
        used.add(slug)
        description = describe(section)
        topics.append(
            Topic(
                slug=slug,
                title=section.title,
                description=description,
                content=_topic_file(section, description),
            )
        )

    parts: list[str] = [_GENERATED_BANNER]
    if preamble:
        parts.append(preamble)
    for section in constraints:
        parts.append(section.text.rstrip())
    if topics:
        parts.append(_render_index(topics, topics_dir))

    core = "\n\n".join(parts).rstrip() + "\n"
    return Projection(core=core, topics=topics, preamble=preamble)


def _render_index(topics: list[Topic], topics_dir: Path | None) -> str:
    """
    The index is the whole read path in phase 1: it carries absolute paths so a
    session can open a topic with ordinary file tools the moment it needs one.
    """
    lines = [
        "## Memory index",
        "",
        "Detail for each area below lives in its own file, not in this context. "
        "Read the file when the topic comes up.",
        "",
    ]
    for topic in topics:
        path = str(topics_dir / f"{topic.slug}.md") if topics_dir else f"{topic.slug}.md"
        lines.append(f"- **{topic.title}** — {topic.description}")
        lines.append(f"  `{path}`")
    return "\n".join(lines)


def check_budget(projection: Projection, config: Config) -> list[str]:
    """
    Return budget violations as human-readable strings. Empty list means the
    core fits.

    This is the check that did not exist: max_hot_lines was only ever
    interpolated into a prompt, so the file ran 2.4x over its stated target
    with nothing objecting.
    """
    problems: list[str] = []
    if projection.core_chars > config.core_max_chars:
        problems.append(
            f"core is {projection.core_chars:,} chars, over the "
            f"{config.core_max_chars:,} budget by "
            f"{projection.core_chars - config.core_max_chars:,}"
        )
    if projection.core_lines > config.max_hot_lines:
        problems.append(
            f"core is {projection.core_lines} lines, over the "
            f"{config.max_hot_lines} budget by "
            f"{projection.core_lines - config.max_hot_lines}"
        )
    return problems


def core_path(memory_root: Path) -> Path:
    return memory_root / CORE_DIRNAME / CORE_FILENAME


def topics_path(memory_root: Path) -> Path:
    return memory_root / CORE_DIRNAME / TOPICS_DIRNAME


def write_projection(projection: Projection, memory_root: Path) -> list[Path]:
    """
    Write the core and topic files, removing any topic file that no longer
    corresponds to a section. Returns the paths written.

    Stale removal is scoped to *.md directly inside topics/ — the directory is
    memsync-owned and regenerated, but the deletion is still kept narrow.
    """
    core = core_path(memory_root)
    topics_dir = topics_path(memory_root)
    topics_dir.mkdir(parents=True, exist_ok=True)

    written: list[Path] = []
    expected = {f"{t.slug}.md" for t in projection.topics}

    for topic in projection.topics:
        target = topics_dir / f"{topic.slug}.md"
        target.write_text(topic.content, encoding="utf-8")
        written.append(target)

    for existing in topics_dir.glob("*.md"):
        if existing.name not in expected:
            existing.unlink()

    core.write_text(projection.core, encoding="utf-8")
    written.append(core)
    return written
