"""
Git-backed history and cross-machine reconciliation for the memory store.

This is deliberately *not* a provider. `BaseProvider` answers one question —
where is the sync root on this machine — and git does not answer it. Git is a
mechanism wrapped around writes: pull before, commit after, and a real merge
instead of a silent fork when two machines disagree.

What it replaces:

  backups/          107 timestamped copies approximating "the previous version"
  journal diffs     hand-rolled diff storage with retention pruning
  sync-conflict-*   Syncthing's response to concurrent writes, which is to fork
                    the file and hope somebody notices

Git does all three properly, and a rejected push is a stricter cross-machine
lock than the advisory one in lock.py, because it cannot be lost to sync
latency.

The one thing it must not do is run inside a live Syncthing folder. Syncthing
replicating .git/ races on the index and packfiles and corrupts the repository,
so git has to replace file-level sync for this directory rather than sit on top
of it. init refuses when it finds Syncthing markers.
"""

from __future__ import annotations

import logging
import subprocess
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)

GITIGNORE = """\
# Generated by memsync.
# Git history supersedes these; keeping them would version the backups too.
backups/
sessions/
.harvest.lock

# Syncthing leftovers. Git resolves concurrent writes by merging, so these
# should stop appearing once file-level sync is off for this folder.
*.sync-conflict-*
.stfolder/
.stignore
"""

_SYNCTHING_MARKERS = (".stfolder", ".stignore", ".stversions")


class StoreError(Exception):
    """A git operation failed in a way the caller must handle."""


@dataclass
class StoreStatus:
    is_repo: bool
    branch: str | None = None
    dirty: bool = False
    remote: str | None = None
    ahead: int = 0
    behind: int = 0
    syncthing: bool = False
    conflict_files: int = 0


def _git(root: Path, *args: str, check: bool = True) -> str:
    """Run a git command in root and return stdout."""
    try:
        result = subprocess.run(
            ["git", "-C", str(root), *args],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
        )
    except FileNotFoundError as exc:  # pragma: no cover - environment dependent
        raise StoreError("git is not installed or not on PATH") from exc
    if check and result.returncode != 0:
        raise StoreError(
            f"git {' '.join(args)} failed ({result.returncode}): "
            f"{(result.stderr or result.stdout).strip()}"
        )
    return result.stdout.strip()


def is_repo(root: Path) -> bool:
    return (root / ".git").exists()


def syncthing_markers(root: Path) -> list[str]:
    """
    Syncthing artefacts in or above the store.

    Checked upward as well: the markers sit at the *folder* root, and the memory
    store is a subdirectory of it, so looking only in the store would miss the
    exact configuration that makes this dangerous.
    """
    found: list[str] = []
    for parent in [root, *root.parents]:
        for marker in _SYNCTHING_MARKERS:
            if (parent / marker).exists():
                found.append(str(parent / marker))
        if parent == parent.parent:
            break
    return found


def conflict_files(root: Path) -> list[Path]:
    return sorted(root.glob("*.sync-conflict-*"))


def status(root: Path) -> StoreStatus:
    """Describe the store. Never raises — this is what diagnostics call."""
    st = StoreStatus(
        is_repo=is_repo(root),
        syncthing=bool(syncthing_markers(root)),
        conflict_files=len(conflict_files(root)),
    )
    if not st.is_repo:
        return st
    try:
        st.branch = _git(root, "rev-parse", "--abbrev-ref", "HEAD")
        st.dirty = bool(_git(root, "status", "--porcelain"))
        remotes = _git(root, "remote", check=False)
        st.remote = remotes.splitlines()[0] if remotes else None
        if st.remote:
            counts = _git(
                root, "rev-list", "--left-right", "--count",
                f"{st.branch}...{st.remote}/{st.branch}", check=False,
            )
            parts = counts.split()
            if len(parts) == 2:
                st.ahead, st.behind = int(parts[0]), int(parts[1])
    except StoreError as exc:
        logger.debug("store status incomplete: %s", exc)
    return st


def init_repo(root: Path, allow_syncthing: bool = False) -> list[str]:
    """
    Initialise the store as a git repository. Returns human-readable steps taken.

    Refuses on a Syncthing folder unless explicitly overridden: replicating
    .git/ byte-for-byte across machines corrupts it, and the failure mode is a
    broken repository rather than a merge conflict you can see coming.
    """
    if is_repo(root):
        raise StoreError(f"{root} is already a git repository")

    markers = syncthing_markers(root)
    if markers and not allow_syncthing:
        raise StoreError(
            "refusing to create a git repository inside a Syncthing folder.\n"
            f"  Found: {', '.join(markers)}\n"
            "  Syncthing replicating .git/ races on the index and packfiles and "
            "corrupts the repository.\n"
            "  Git must replace file-level sync for this folder, not run beside "
            "it: stop sharing it in Syncthing first, then re-run.\n"
            "  Use --allow-syncthing only if you have already stopped sharing it "
            "and the markers are leftovers."
        )

    steps: list[str] = []
    _git(root, "init")
    steps.append("initialised repository")

    gitignore = root / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(GITIGNORE, encoding="utf-8")
        steps.append("wrote .gitignore")

    _git(root, "add", "-A")
    if _git(root, "status", "--porcelain"):
        _git(root, "commit", "-m", "memsync: initial store snapshot")
        steps.append("committed initial snapshot")
    return steps


def snapshot(root: Path, message: str) -> str | None:
    """
    Commit the current state. Returns the commit hash, or None if nothing
    changed.

    Never raises on a non-repo or a failed commit: a memory write that already
    succeeded must not be reported as a failure because history-keeping did not.
    The write is the product; the commit is bookkeeping.
    """
    if not is_repo(root):
        return None
    try:
        _git(root, "add", "-A")
        if not _git(root, "status", "--porcelain"):
            return None
        _git(root, "commit", "-m", message)
        return _git(root, "rev-parse", "--short", "HEAD")
    except StoreError as exc:
        logger.warning("store snapshot failed (memory write itself succeeded): %s", exc)
        return None


def pull(root: Path) -> str:
    """
    Bring in remote changes, rebasing local commits on top.

    A rebase that hits a conflict is aborted rather than left half-applied. A
    store in a conflicted rebase state is one no other memsync command can
    safely write to, so the failure is surfaced whole instead of partially
    resolved.
    """
    st = status(root)
    if not st.remote:
        return "no remote configured; nothing to pull"
    try:
        _git(root, "pull", "--rebase", st.remote, st.branch or "HEAD")
    except StoreError as exc:
        _git(root, "rebase", "--abort", check=False)
        raise StoreError(
            f"pull failed and the rebase was aborted, so the store is unchanged: {exc}"
        ) from exc
    return f"pulled from {st.remote}"


def push(root: Path) -> str:
    st = status(root)
    if not st.remote:
        return "no remote configured; nothing to push"
    _git(root, "push", st.remote, st.branch or "HEAD")
    return f"pushed to {st.remote}"
